name: build-linux

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install musl-tools -y

      - name: Build static Linux binary (amd64)
        run: |
          mkdir -p build
          export CC=musl-gcc
          export CGO_ENABLED=1
          export GOOS=linux
          export GOARCH=amd64
          go build -trimpath -ldflags "-s -w --extldflags '-static'" -o build/app-linux-amd64 .

      - name: Compress binary
        run: |
          cd build
          tar -czf app-linux-amd64.tar.gz app-linux-amd64

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


